    training_devenv_img:        
        build: ./docker/build/
        ports:
            - "80:80"            
        volumes:    
        - ./src:/var/www/html  
        - ./docker/build/install:/root/install            
        - ./docker/build/conf/apache2/apache2.conf:/etc/apache2/apache2.conf
        # command: [ "/root/install/init.sh" ]
        container_name: training_devenv_ctn






